config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:'',:path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root to: "dashboard/posts#new"

  get "/dashboard" => 'dashboard/posts#new', as:"dashboard"
  namespace :dashboard do
    resources :posts, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :tags, only:[:index,:new,:create,:edit,:show,:update,:destroy]

  	get "/about" => '/dashboard/about#get'
  	post "/about" => '/dashboard/about#post'
  	patch "/about" => '/dashboard/about#post'

  end

  get "/api/posts" => 'api/posts#all', as:"api"

  # Added for public view - for twitter cards
  get "/posts/:id" => 'posts#show'
  match '*any' => 'application#options', :via => [:options]

end

app/models/about.rb
class About < ActiveRecord::Base
	validates_presence_of :content
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :title
	mount_uploader :image, ImageUploader
	has_many :tag_posts, dependent: :delete_all
	has_many :tags, through: :tag_posts
	validates_uniqueness_of :title

	def assign_shortcode
		if !self.shortcode.present?
			self.shortcode = "$$MPV"+self.id.to_s
			self.save
		else
			if self.shortcode[0] != '$' && self.shortcode[1] != '$'
				self.shortcode.prepend("$$")
				self.save
			end
		end
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	validates_presence_of :name
	validates_uniqueness_of :name
	has_many :tag_posts
	has_many :posts, through: :tag_posts
end

app/models/tag_post.rb
class TagPost < ActiveRecord::Base
	belongs_to :tag
	belongs_to :post
		
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/posts_controller.rb
module Api
	class PostsController < ApplicationController
		skip_before_filter :verify_authenticity_token
		def all
			posts = Post.all
			about = About.all.first
			json = {
				posts: posts.to_json(:include => :tags),
				about: about.to_json

			}
		 	render :json => json	
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :assign_layout
  layout :assign_layout
  before_filter :add_allow_credentials_headers

    def add_allow_credentials_headers                                                                                                                                                                                                                                                        
      # https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#section_5                                                                                                                                                                                                      
      #                                                                                                                                                                                                                                                                                       
      # Because we want our front-end to send cookies to allow the API to be authenticated                                                                                                                                                                                                   
      # (using 'withCredentials' in the XMLHttpRequest), we need to add some headers so                                                                                                                                                                                                      
      # the browser will not reject the response                                                                                                                                                                                                                                             
      response.headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || '*'                                                                                                                                                                                                     
      response.headers['Access-Control-Allow-Credentials'] = 'true'                                                                                                                                                                                                                          
    end 

    def options                                                                                                                                                                                                                                                                              
      head :status => 200, :'Access-Control-Allow-Headers' => 'accept, content-type'                                                                                                                                                                                                         
    end
    def assign_layout
        if admin_dashboard_mode
            'dashboard'
      	end
  	end
  	def admin_dashboard_mode
    	self.class.parent == Dashboard
  	end

    def after_sign_in_path_for(resource)

      '/dashboard'
    end
end

app/controllers/dashboard/about_controller.rb
module Dashboard
	class AboutController < ApplicationController
		include ApplicationHelper
    	before_filter :check_admin?
    	def get
    		if About.all.first.present?
    			@about = About.all.first
    		else
    			@about = About.new
    		end
    	end  
        def post
            if About.all.first.present?
                @about = About.all.first
            else
                @about = About.new()
            end
            if @about.update(about_params)
                redirect_to "/dashboard/about"
            else
                redirect_to "/dashboard/about", alert: "There was an error with your form"
            end


        end
        private 
        def about_params
          params.require(:about).permit(:content)
        end
	end
end

app/controllers/dashboard/posts_controller.rb
module Dashboard
	class PostsController < ApplicationController
		include ApplicationHelper
    	before_filter :check_admin?
		def index
			@posts = Post.all
	 	end
		def new
			@post = Post.new
		end
		def create
			@post = Post.new(post_params)
			
			if @post.save
				@post.assign_shortcode
				redirect_to dashboard_posts_path
			else
				render :json => {errors: @post.errors.full_messages}	
			end
		end
		def edit
			@post = Post.find(params[:id])

		end
		def update
			@post = Post.find(params[:id])
			@post.update(post_params)
			if @post.save
				@post.assign_shortcode
				redirect_to dashboard_posts_path
			else
				redirect_to edit_dashboard_post_path(@post.id)
			end
		end
		def show
		end
		def destroy
			Post.find(params[:id]).delete
			redirect_to dashboard_posts_path
		end
		private	
  		def post_params
	      params.require(:post).permit(:title,:description,:shortcode,:image,:tag_ids => [])
	    end
	end
end

app/controllers/dashboard/tags_controller.rb
module Dashboard
	class TagsController < ApplicationController
				include ApplicationHelper
    	before_filter :check_admin?
		def index
			@tags = Tag.all
			@tag = Tag.new
		end
		def show
			@posts = Tag.find(params[:id]).posts
		end
		def new
			@tag = Tag.new
		end
		
		def create
			@tag = Tag.new(tag_params)
			if @tag.save
				redirect_to dashboard_tags_path
			else
				redirect_to dashboard_tags_path, notice: @tag.errors
			end
		end

		def edit
		end
		def update
		end
		def destroy
			Tag.find(params[:id]).delete
			redirect_to dashboard_tags_path
		end
		private	
  		def tag_params
	      params.require(:tag).permit(:name,:post_ids => [])
	    end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    sim = []
    @similar = []
    @post.tags.each do |t|
    	t.posts.each do |p|
			if p.id != @post.id
				sim << p
			end
    	end
    end
    @similar = sim.uniq{|x| x.id}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def check_admin?
        unless current_user
            redirect_to "/login"
            return
        end
    end
end

app/views/dashboard/about/get.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>About</strong> <small></small>
		</div>
	<div class="panel-body">
		<%= simple_form_for @about, url: "/dashboard/about"  do |f| %>
			<%= f.input :content, required: true %>
		   
			<%= submit_tag 'Save', class: "btn btn-default" %>


		<%end%>

	</div>
</div>

app/views/dashboard/posts/_post_form.html.erb
<%= simple_form_for @post, url: @post.id.present? ? dashboard_post_path(@post.id) : dashboard_posts_path ,:html=>{id: :postForm}, remote: true do |f| %>
	
		<div class="form-group">
			<%= f.input :title, required: true, placeholder:"Title of your infographic" %>
		</end>

		<div class="form-group">
			 <%= f.file_field :image, id: 'js-upload-files' %>
			<h4>Or drag and drop files below</h4>
			<div class="upload-drop-zone" id="drop-zone">
			<% if @post.image_url.present? %>	
              	<img id="preview" src="<%=@post.image_url%>" alt="">

			<%else%>
				Just drag and drop files here
			<%end%>
			</div>
		</div>
		<div class="form-group">
	    	<%= f.association :tags, :include_hidden => false, input_html: { class: 'multi-select' }  %>
	   	</div>
	   	<div class="form-group">
	   		<%= f.input :description, placeholder:"This is some descriptive text about the infographic you just uploaded. The more information the better.  Include links to the source and other relevant information"  %>
	   	</div>
	   	<div class="form-group">
	   		<%= f.input :shortcode, placeholder:"$$PoliceViolence" %>
	   	</div>
		<%= submit_tag 'Save', class: "btn btn-sm btn-primary", id:"js-upload-submit" %>
		
		<% if @edit %>
			<%= link_to "delete", {:controller => :posts, :action => 'destroy', :id => @post.id }, :method => :delete, class: "btn btn-danger" %>
		<%end%>

<%end%>
<script>
 	var file
$(document).ready(function(){
    console.log('yo');
    'use strict';
    var dropZone = document.getElementById('drop-zone');
    var uploadForm = document.getElementById('postForm');

    var startUpload = function(files) {
        file=files
        
        if (file != undefined) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#drop-zone").html('<img id="preview" src="#" alt="" />')
                $('#preview').attr('src', e.target.result);
                
            }
            reader.readAsDataURL(file[0]);
        }
    }

    uploadForm.addEventListener('submit', function(e) {
        e.preventDefault()
        e.stopImmediatePropagation();
        var $form = $(this),
                formData = new FormData(),
                params   = $form.serializeArray()
        if (file != undefined){
             formData.append('post[image]', file[0]);
        }else{
             formData.append('post[image]', $("#js-upload-files")[0].files[0]);
        }
       
        $.each(params, function(i, val) {
            formData.append(val.name, val.value);        
        });

        $.ajax({
            url: $form.attr('action'),
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            type: 'POST',
            success: function(result) {
                if (result.errors != undefined){
                     $("#alert-modal .modal-title").html("Error")
                     $("#alert-modal .modal-body").html("Please review your post.")
                }else{
                     $("#alert-modal .modal-title").html("Thanks")
                     $("#alert-modal .modal-body").html("<a href ='/dashboard/posts'>See all posts here</a>")
                }   
               
                $("#alert-modal").modal()
                $('form')[0].reset();
                file = "";
                
                $('#preview').attr('src',"");
            }
        });
        return false;  
    })

    dropZone.ondrop = function(e) {
        e.preventDefault();
        this.className = 'upload-drop-zone';

        startUpload(e.dataTransfer.files)
    }

    dropZone.ondragover = function() {
        this.className = 'upload-drop-zone drop';
        return false;
    }

    dropZone.ondragleave = function() {
        this.className = 'upload-drop-zone';
        return false;
    }
$('.multi-select').multiselect({enableFiltering: true});

});
	</script>

app/views/dashboard/posts/_show_posts.html.erb
<div class="row " id="card-container">
	<% @posts.each do |p| %>
		<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 card">
			<div class="card-wrapper">

				 <div class="title "><%= p.title %></div>
				 	 <div class="categories">
				 	<span class='bold'>Tags: </span>
				 	<% p.tags.each do |tag| %>
				 	  <a href="<%=dashboard_tag_path(tag.id)%>"><%=tag.name%></a> | 
				 	<%end%>
				 </div>

				 <div class="line"></div>
				<% if p.image%>
					<div class="media ">
						<a href="<%= edit_dashboard_post_path(p.id)%>">
							<img src="<%= p.image_url %>" alt="">
						</a> 
					</div>
				<% end %>
				 <div class="line"></div>
				 <div class="delete">
					<%= button_to "delete", {:controller => :posts, :action => 'destroy', :id => p.id }, :method => :delete, class: "btn btn-danger btn-sm" %>
				</div>
		

			</div>
		</div>
	<% end %>
</div>

app/views/dashboard/posts/edit.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong><%=@post.title%></strong> <small></small>
		</div>
	<div class="panel-body">
		<%= render 'dashboard/posts/post_form' %>
	</div>
</div>

app/views/dashboard/posts/index.html.erb
<ul>
    <% @posts.each do |post|  %>
    	<li><%= post.title%> </li>
    <%end%>
</ul>

app/views/dashboard/posts/new.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Upload Files</strong> <small></small>
		</div>
	<div class="panel-body">
		<%= render 'dashboard/posts/post_form' %>
	</div>
</div>

app/views/dashboard/tags/_tag_form.html.erb
<%= simple_form_for @tag, url: dashboard_tags_path do |f| %>
	<%= f.input :name, required: true %>
    <%= f.association :posts, :include_hidden => false, input_html: { class: 'multi-select' }  %>

	<%= submit_tag 'Save', class: "btn btn-default" %>
	
	<% if @edit %>
		<%= link_to "delete", {:controller => :posts, :action => 'destroy', :id => @post.id }, :method => :delete, class: "btn btn-danger" %>
	<%end%>

<%end%>
<script>

	$('.multi-select').multiselect({enableFiltering: true});
</script>

app/views/dashboard/tags/index.html.erb
<div class="container">
<table class="categories-table editable-table table table-striped table-bordered no-footer">
  <thead>
    <tr class='category-table-header'>
      <th class="table-header category-name">Name</th>
      <th class="table-header category-name">Post Count</th>
      <th class="table-header delete">Delete</th>
    </tr>
  </thead>
  <tbody>
  <% @tags.each_with_index do |c, i| %>
    <tr class="category-row-<%=i%>" id="<%=c.id%>">
      <td
        ><span href='#' data-resource='categories' data-type="text" data-editable='name'><%= c.name %></span
        ><span class='toggle-edit'>+</span>
      </td>
      <td><%= c.posts.count %></td>
      <td><%= button_to "delete", {:controller => :tags, :action => 'destroy', :id => c.id }, :method => :delete, class: "btn btn-danger btn-sm" %></td>
    </tr>

  <%end%>
  </tbody>
</table>

	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Add New Tag</strong> <small></small>
		</div>
	<div class="panel-body">
		<%= render 'dashboard/tags/tag_form' %>
	</div>
</div>

app/views/dashboard/tags/new.html.erb
<%= render 'dashboard/tags/tag_form' %>

app/views/dashboard/tags/show.html.erb
<%= render 'dashboard/posts/show_posts' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampaignZeroV1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for?(:title) ? yield(:title) : "Mapping Police Violence - Admin" %></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

   <title>CampaignZero Admin Dashboard</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body class='admin-dashboard'>
<div class="container">
    <%= render 'layouts/menus/dashboard_menu' %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <%= yield %>
    <div id="alert-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 

app/views/layouts/menus/_dashboard_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mapping Police Violence</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/dashboard">Upload</a></li>
            <li><a href="/dashboard/posts">Dashboard</a></li>
            <li><a href="/dashboard/tags">Tags</a></li>
            <li><a href="/dashboard/about">About</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Logout" , destroy_user_session_path, method: :delete %></li>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/posts/show.html.erb
<meta charset="UTF-8">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@tweetercards">
<meta name="twitter:creator" content="@tweetercards">
<meta name="twitter:title" content="<%=@post.title%>">
<meta name="twitter:description" content="<%=@post.title%>">
<meta name="twitter:image" content="<%= root_url + @post.image_url%>">

<style>
header{text-align: center;}
 img{
 	width:500px;
 	max-width:100%;
 	max-height:100%;
 }
 .thumbnail img{
 	height:300px;
 }
</style>
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1><%=@post.title%></h1>
            <p><%= image_tag @post.image_url %></p>

            <p><%= @post.description %></p>
            <p><% if current_user.present? %>
            	<a href="/dashboard/posts/<%=@post.id%>/edit" class="btn btn-primary btn-large">Edit</a>
                <%end%>
            </p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Similar Posts</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">
        	<% if @similar.present? %>
        	<% @similar.each do |p| %>
	            <div class="col-md-3 col-sm-6 hero-feature">
	                <div class="thumbnail">
	                    <%= image_tag p.image_url %>
	                    <div class="caption">
	                        <h3><%=p.title%></h3>
	                        <p><%= p.description.present? ? p.description : "No description" %></p>
	                        <p>
	                        	<% if current_user.present? %>
	                            <a href="/dashboard/posts/<%=p.id%>/edit" class="btn btn-primary">Edit</a>
	                            <%end%>
	                             <a href="/posts/<%=p.id%>" class="btn btn-default">See Post</a>
	                        </p>
	                    </div>
	                </div>
	            </div>
	        <%end%>
	        <%end%>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Campaign Zero 2016</p>
                </div>
            </div>
        </footer>

    </div>





<%= root_url + @post.image_url %>